### ISSUE TITLE
Fixer.io API Endpoint Deprecation

### ISSUE THREAD

**Issue by philwinkle** [philwinkle/Philwinkle_Fixerio#22]
API is currently scheduled for deprecation on June 1, 2018. 

- Migrate to new endpoint
- Provide support until new endpoint EOL

Message currently being returned:

```
{"__deprecation_message__":"This API endpoint is deprecated and will stop working on June 1st, 2018. For more information please visit: https://github.com/fixerAPI/fixer#readme","base":"USD","date":"2018-04-16","rates":{"EUR":0.80841}}
```

**Comment by df2k2** [comment]
Considering this has been useful for me, I'd be smart to help out.  From what I've read, there isn't much work needed here.  https://github.com/fixerAPI/fixer indicates:

> The core structure of the old API has remained unchanged, and you will only need to perform a few simple changes to your integration.

**Comment by sprankhub** [comment]
@df2k2 any idea when you will be able to implement it? It should be quite straightforward as support for the access key parameter has already been implemented in 4f3d5258561d36b20266dd11886a787dab639fc6.

**Comment by df2k2** [comment]
@sprankhub and @philwinkle - We've got a problem.  The new API requires a paid subscription ($10/month) to set the base currency to anything other than the default, which is **EUR**.

For example: `http://data.fixer.io/api/latest?access_key=...&symbols=CAD&base=USD` returned the following: 
`{"success":false,"error":{"code":105,"type":"base_currency_access_restricted"}}`

-----
I also have found a mention of that (https://github.com/fixerAPI/fixer), while verifying the limitation:

> Fixer is still free! Although we now offer a set of premium plans for more advanced users, the basic API features (e.g. getting the latest and historical exchange rates) remain completely free of charge. **Minor limitations include our new 1000 requests/month limit and EUR being the only available base currency for customers using a free account.** If you need more than 1000 requests per month or want to use all 170 available base currencies, you’ll need to choose one of the paid plans starting at only $10 per month.

-----

I had the thought of converting between currencies using the information obtained freely.  It seems that anyone using the current soon-to-be deprecated API, won't experience much of a problem from it.

**For example:**

0.874801 GBP = 1 EUR = 1.224286 USD

Could have exchange rates calculated as: 
**1 USD** = ((0.874801 GBP to 1 EUR)/(1.224286 USD to 1 EUR)) = **0.714540 GBP**

and inversely as: 
**1 GBP** = ((1.224286 USD to 1 EUR)/((0.874801 GBP to 1 EUR)) = **1.399502 USD**

Thoughts?

**Comment by sprankhub** [comment]
Shit. Thanks for your research! I shortly researched different services, but they all seem to have the same limits. Anyway, your suggestion sounds good to me @df2k2! Will you implement it?

**Comment by df2k2** [comment]
@sprankhub - I can definitely implement it.  I think it would also be beneficial to implement a check for subscription-level to determine if we can use the method that allows for a base currency parameter.  If not a check for a subscription-level, then a first attempt using the `base` currency parameter, with a fall-back to the conversion.
Sound good?
I can have it implemented by early next week.

**Comment by sprankhub** [comment]
Sounds good! Either with a config option, where you can choose your subscription type (free vs. paid) or you are able to determine that via the API. Thanks @df2k2!

**Comment by df2k2** [comment]
@sprankhub - I have begun working on the update.   Here are a couple updates:

**Accuracy of Conversion**
I have triple-checked the accuracy of the 'converted' rates and they appear to be more accurate, cross-referenced with those on https://www.xe.com/, than the rates from the current soon-to-be-deprecated API. 

| From | To  | Converted (New API) | XE.com | Legacy API |
| ----- | ----- | ---- | ---- | ---- |
| 1 USD | GBP | 0.72554 |  0.72547 | 0.72659 |
| 1 USD | AUD | 1.32040 | 1.32003 | 1.32350 |

**API Usage Estimates**

Currently, each conversion would cost one API call.   I had an initial concern about reaching the limit of API calls per month, but I've since determined that to not really be a concern.  I took an example where a  platform that would support five currencies and make five daily conversions, would result in roughly 750 monthly API calls.  

Initially, I had begun to implement the updated methods to obtain all the rates for system config's 'allowed currencies', then traverse that array in order to reduce the number of API calls.   I've decided to shelve those changes for now.

**Final Updated Decisions**

Given the accuracy of exchange rates to three digits after the decimal place (thousandths) using the free method with the conversion math, I've decided to shelve the changes I have begun making that support paid accounts.  If a user would like this feature to be implemented, then they can request it.

**Comment by df2k2** [comment]
Updated and tested.
![firefox_screenshot_2018-04-27t20-22-59 644z](https://user-images.githubusercontent.com/4868368/39383475-5b961ff6-4a37-11e8-8692-4a9aacbf32fc.png)

**Comment by df2k2** [comment]
@sprankhub and @philwinkle 
Feel free to let me know what I should fix or change...  I've removed the legacy endpoint, primarily because I couldn't think of a reason to keep it.

I can see a few faults in the code I've applied...  The one that's bugging me the most is the rounding function and precision.   The precision shouldn't be a constant value, so I'm removing that.

I've made additional changes and will request some assistance with the rounding and significant decimal precision.

-------

**Note:** The new API endpoint will not permit the HTTPS protocol for a free account.  HTTP is used.

**Comment by philwinkle** [comment]
Closed with #23! Thanks @df2k2

**Comment by sprankhub** [comment]
Thanks again @df2k2! One thing, which came into my mind: Shouldn't the API key be stored encrypted?

**Comment by df2k2** [comment]
@sprankhub - Should it be encrypted?  Yes, absolutely.

Something similar to this, yes?

```
    /**
     * Encrypt data
     *
     * @param   string $data
     * @return  string
     */
    public function encrypt($data)
    {
        if ($data) {
            return Mage::helper('core')->encrypt($data);
        }
        return $data;
    }

    /**
     * Decrypt data
     *
     * @param   string $data
     * @return  string
     */
    public function decrypt($data)
    {
        if ($data) {
            return Mage::helper('core')->decrypt($data);
        }
        return $data;
    }
```

**Comment by sprankhub** [comment]
@df2k2 something like this, yes. But I think you do not need the `encrypt` method. It should be enough to define the backend model of the config value:

    <backend_model>adminhtml/system_config_backend_encrypted</backend_model>

Then you only need to `decrypt` properly after `Mage::getStoreConfig`.

**Comment by df2k2** [comment]
@sprankhub,

Thanks for the guidance here.  I've applied the update and opened a pull request for @philwinkle.

**Comment by mmenozzi** [comment]
Hi @philwinkle, could you please tag a new stable version including the new API endpoint support?

**Comment by philwinkle** [comment]
@mmenozzi done. See v0.4.0

**Comment by mmenozzi** [comment]
Thank you @philwinkle!

**Comment by InternetAdvertisingSolutions** [comment]
We updated on Magento 1.9.2.4 and while the manual updating of currencies works fine, the automatic scheduled rate update doesn't update the rates.  The API is being polled daily as we can see on our accounts at fixer.io but the rates have not changed in 2 days, no currency update failed emails.

**Comment by kkazadi** [comment]
I'm Having a bit of problem getting my head around the API Calls, I have subscribed to a Professional Plan - monthly (100,000) on a Magento multi stores as per my screen shot below, but i keep running out  of my monthly requests, i don't know how to lower these api calls down, can someone please shade some light here?

![Currency_Fixer io](https://user-images.githubusercontent.com/23381441/63759036-1ea4c600-c8bd-11e9-94f2-baff94b524ea.png)

**Comment by df2k2** [comment]
> 
> 
> I'm Having a bit of problem getting my head around the API Calls, I have subscribed to a Professional Plan - monthly (100,000) on a Magento multi stores as per my screen shot below, but i keep running out of my monthly requests, i don't know how to lower these api calls down, can someone please shed some light here?


Yikes... I see a possible 36 api requests in your list, however, 6 of them would be 1:1=1.000 (ie, AUD:AUD, EUR:EUR), etc...  So that would mean your limit is hit after 2778 times of all 36 items being requested.  That's certainly not correct.  How often do you have the scheduling of updates done?  Do you know if there are CRON jobs handling this?  How often do they run..   Are you updating this real time?  Do you think someone may have compromised your key?

**Comment by df2k2** [comment]
The algorithm can definitely be updated to be more efficient -- for example, using the free-version:

http://data.fixer.io/api/latest?access_key=<accesskey>&symbols=USD,GBP,EUR,AUD,NZD,ZAR

yields:

```json 
{
  "success": true,
  "timestamp": 1566918126,
  "base": "EUR",
  "date": "2019-08-27",
  "rates": {
    "USD": 1.110063,
    "GBP": 0.90418,
    "EUR": 1,
    "AUD": 1.6416,
    "NZD": 1.74335,
    "ZAR": 17.01948
  }
}
```

Since 0.90418 GBP =1 EUR = 1.6416 AUD, we could divide GBP/AUD to obtain the (top row) GBP to  (left side) AUD exchange rate: 

0.90418 GBP / 1.6416 AUD = 0.550791910331384 
TOP / LEFT = Exchange Rate

0.550791910331384 GBP = 1 AUD

| Symbol | AUD | EUR | GBP | NZD | USD | ZAR |
| ---- | ---- | ----- | ---- | ---- | ---- | ---- |
| AUD | 1.6416/1.6416 | /1.6416 | /1.6416 | /1.6416 | /1.6416 | /1.6416 |
| EUR | 1.6416/1 |  | 0 | 0 | 0 | 0 |
| GBP | 1.6416/0.90418 | 1/0.90418 | 0.90418/0.90418 | 1.74335/0.90418 | 1.110063/0.90418 | 17.01948/0.90418 |
| NZD| 0 | 0 | 0 | 0 | 0 | 0 |
| USD | 0 | 0 | 0 | 0 | 0 | 0 |
| ZAR | 0 | 0 | 0 | 0 | 0 | 0 |

---------

Looking at the numbers you have obtained from your pro-account and using the formulas, I've exactly calculated the values in your chart.

Therefore, we would only need to obtain 1 base currency, and it's exchange rate for each other currency -- the rest would be calculated without any difference in value obtained from API.

**Comment by kkazadi** [comment]
> > I'm Having a bit of problem getting my head around the API Calls, I have subscribed to a Professional Plan - monthly (100,000) on a Magento multi stores as per my screen shot below, but i keep running out of my monthly requests, i don't know how to lower these api calls down, can someone please shed some light here?
> 
> Yikes... I see a possible 36 api requests in your list, however, 6 of them would be 1:1=1.000 (ie, AUD:AUD, EUR:EUR), etc... So that would mean your limit is hit after 2778 times of all 36 items being requested. That's certainly not correct. How often do you have the scheduling of updates done? Do you know if there are CRON jobs handling this? How often do they run.. Are you updating this real time? Do you think someone may have compromised your key?

I have schedule this in Magento to run every day which runs through Magento cron jobs, i have now changed to run weekly but haven't seen any results as yet since i've already ran out of monthly limits, 
No i don't think someone may have compromised my key.

**Comment by kkazadi** [comment]
> The algorithm can definitely be updated to be more efficient -- for example, using the free-version:
> 
> http://data.fixer.io/api/latest?access_key=&symbols=USD,GBP,EUR,AUD,NZD,ZAR
> 
> yields:
> 
> ```json
> {
>   "success": true,
>   "timestamp": 1566918126,
>   "base": "EUR",
>   "date": "2019-08-27",
>   "rates": {
>     "USD": 1.110063,
>     "GBP": 0.90418,
>     "EUR": 1,
>     "AUD": 1.6416,
>     "NZD": 1.74335,
>     "ZAR": 17.01948
>   }
> }
> ```
> 
> Since 0.90418 GBP =1 EUR = 1.6416 AUD, we could divide GBP/AUD to obtain the (top row) GBP to (left side) AUD exchange rate:
> 
> 0.90418 GBP / 1.6416 AUD = 0.550791910331384
> TOP / LEFT = Exchange Rate
> 
> 0.550791910331384 GBP = 1 AUD
> 
> Symbol	AUD	EUR	GBP	NZD	USD	ZAR
> AUD	1.6416/1.6416	/1.6416	/1.6416	/1.6416	/1.6416	/1.6416
> EUR	1.6416/1		0	0	0	0
> GBP	1.6416/0.90418	1/0.90418	0.90418/0.90418	1.74335/0.90418	1.110063/0.90418	17.01948/0.90418
> NZD	0	0	0	0	0	0
> USD	0	0	0	0	0	0
> ZAR	0	0	0	0	0	0
> Looking at the numbers you have obtained from your pro-account and using the formulas, I've exactly calculated the values in your chart.
> 
> Therefore, we would only need to obtain 1 base currency, and it's exchange rate for each other currency -- the rest would be calculated without any difference in value obtained from API.

Can the above solution be implemented and committed the plugin for M1? Or would this lower my call requests if i just schedule from Magento back-end to run weekly?

**Comment by kkazadi** [comment]
So, I have setup my Magento cron job to run every 5 mins, and reason for this is because of Magento order transnational emails, now i can see that whenever i enable the scheduled import settings for Fixer.io in the back end, this runs every 5 min which costs about 30 API usage no matter what the frequency is set to (daily, weekly or monthly). can you please advise if there is a way to set a specific cron job only for Fixer.io ?

**Comment by AnmolTomer** [comment]
Someone came up with a free version to do this. You can check it here. https://exchangeratesapi.io/
